# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='yemekfıyatı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='yemekresmı',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
